import { InvoiceBrowser, SqliLogin, SqliSearch } from "../components/SimBrowser";
import {
  CorsLab,
  CmdPing,
  DomXss,
  JwtForgery,
  MassAssign,
  NosqlLogin,
  OpenRedirect,
  SsrfFetch,
  SstiLab,
  TraversalViewer,
  UploadHub,
  XxeLab,
  XssGuestbook,
} from "../components/VulnApps";
import { SQLI_LOGIN_ANSWERS } from "./sim";

export const VULN_FILTERS = [
  { id: "all", label: "All treasures" },
  { id: "injection", label: "Injection" },
  { id: "access", label: "Access Control" },
  { id: "ssrf", label: "SSRF" },
  { id: "integrity", label: "Integrity" },
];

export const PlaygroundApps = [
  {
    id: "novabank",
    name: "NovaBank",
    category: "Broken Access Control · OWASP #1",
    filter: "access",
    goal: "Edit the URL bar: change id=1042 → id=1041 and read another customer's invoice. Capture the flag inside it.",
    flag: "FLAG{n0_0wn3rsh1p_ch3ck}",
    hint: "Invoices are sequential. Yours is 1042 — try one less.",
    learn:
      "IDOR: the app checks that you're logged in but never checks that the invoice belongs to you. Sequential ids make every other customer one guess away. Fix: verify ownership on every request and use unpredictable ids.",
    render: ({ onReveal }) => <InvoiceBrowser hunt onReveal={onReveal} />,
  },
  {
    id: "shoplift-login",
    name: "ShopLift · Sign In",
    category: "Injection · OWASP #5",
    filter: "injection",
    goal: "Bypass the login. Type a payload into the username field that makes the WHERE clause always TRUE.",
    flag: "' OR '1'='1",
    hint: "Close the quote, then OR something that's always true.",
    learn:
      "SQL Injection: the query is built by pasting your username into the SQL string. Closing the quote turns your input into code, and OR '1'='1 makes the WHERE clause always true — no password needed. Fix: prepared statements.",
    render: ({ onReveal }) => (
      <SqliLogin answers={SQLI_LOGIN_ANSWERS} onLoggedIn={onReveal} />
    ),
  },
  {
    id: "shoplift-search",
    name: "ShopLift · Search",
    category: "Injection · OWASP #5",
    filter: "injection",
    goal: "Dump the users table. Use a UNION SELECT that matches the 3 columns to reveal the admin flag.",
    flag: "FLAG{7h3y_trust3d_th3_1nput}",
    hint: "1' UNION SELECT 1, username, password FROM users#",
    learn:
      "UNION Injection: UNION appends a second SELECT to the original query. Match the column count and you can read any table — here, usernames and password hashes. Fix: prepared statements + least-privilege DB accounts.",
    render: ({ onReveal }) => <SqliSearch onReveal={onReveal} />,
  },
  {
    id: "sqli-blind",
    name: "ShopLift · Blind Search",
    category: "Blind SQLi · OWASP #5",
    filter: "injection",
    difficulty: "medium",
    goal: "No results are ever printed — only TRUE/FALSE. Inject a payload that makes the query TRUE and confirm it.",
    flag: "FLAG{bl1nd_tru3_f4ls3}",
    hint: "Make the WHERE clause always true: ' OR '1'='1'-- then watch the count flip to TRUE.",
    learn:
      "Blind SQLi: the app swallows errors and rows, so you extract data one yes/no answer at a time (boolean or time-based). It's slower but just as dangerous. Fix: parameterized queries — never assemble SQL from strings.",
    render: () => null,
  },
  {
    id: "sqli-union",
    name: "ShopLift · UNION Search",
    category: "UNION SQLi · OWASP #5",
    filter: "injection",
    difficulty: "medium",
    goal: "The search leaks error text and merges result sets. Use UNION SELECT to pull usernames and passwords out of the users table.",
    flag: "FLAG{un10n_s3l3ct_0nly}",
    hint: "' UNION SELECT username, password FROM users--",
    learn:
      "UNION-based SQLi: append a second SELECT that matches the original column count, and the database returns your rows in the same result set — no need to guess output placement. Fix: prepared statements, encoded output, least-privilege DB accounts.",
    render: () => null,
  },
  {
    id: "sqli-waf",
    name: "ShopLift · WAF Login",
    category: "SQLi WAF Bypass · OWASP #5",
    filter: "injection",
    difficulty: "medium",
    goal: "A WAF blocks classic keywords (or, and, --, union). Login anyway using an operator the filter misses.",
    flag: "FLAG{w4f_0nly_l00ks_f0r_f34r_w0rdz}",
    hint: "MySQL's || is a logical OR that the word filter doesn't catch: admin'||'1'='1",
    learn:
      "WAF bypass: keyword blacklists are fragile — || (logical OR in MySQL), hex encoding, and comments evade them. WAFs add defense-in-depth but never replace parameterized queries. Fix: prepared statements + a WAF with behavioral, not just signature, rules.",
    render: () => null,
  },
  {
    id: "priv-esc",
    name: "ShopLift · Admin Console",
    category: "Privilege Escalation · OWASP #1",
    filter: "access",
    difficulty: "medium",
    goal: "A role-gated admin console reads your role from the session cookie. Elevate yourself and open it.",
    flag: "FLAG{3l3vat3d_2_admin}",
    hint: "The server trusts the unsigned JWT in the session cookie. Forge a token with role=admin in the cookie jar (or via the Session page).",
    learn:
      "Privilege escalation via forged tokens: when the server trusts client-supplied session data without verifying a signature, any user can mint an admin role. Fix: verify the signature/secret server-side, rotate keys, never store authorization in an unsigned cookie.",
    render: () => null,
  },
  {
    id: "xss-guestbook",
    name: "VibeChat · Guestbook",
    category: "Stored XSS · OWASP #3",
    filter: "injection",
    goal: "Stored XSS: leave a comment containing a <script> tag. When it 'runs' in the page, you capture the flag.",
    flag: "FLAG{5cr1pt_k1dd13_f0und_u}",
    hint: "Comments render as raw HTML. Try posting <script>alert('pwned')</script>",
    learn:
      "Stored XSS: the site saves your comment and renders it with raw HTML, so a <script> in it executes for every visitor — stealing cookies and sessions. Fix: escape all output and use a safe rendering engine.",
    render: ({ onReveal }) => <XssGuestbook onReveal={onReveal} />,
  },
  {
    id: "cmd-ping",
    name: "NetPing · Diagnostics",
    category: "Command Injection · OWASP #3",
    filter: "injection",
    goal: "Command injection: your target is pasted into a shell command. Chain another command to read the server secret.",
    flag: "FLAG{p1ng_3x3c_4rby}",
    hint: "A semicolon ends the ping and starts your command — try ; whoami",
    learn:
      "Command Injection: the app runs `ping -c 4 <input>` directly in the shell. A semicolon or pipe lets an attacker chain arbitrary commands with the server's privileges. Fix: never pass user input to shell commands; validate strictly.",
    render: ({ onReveal }) => <CmdPing onReveal={onReveal} />,
  },
  {
    id: "path-traversal",
    name: "DocVault · File Viewer",
    category: "Path Traversal · OWASP #1",
    filter: "access",
    goal: "Path traversal: the file parameter maps to a server folder. Break out of it to read /etc/passwd.",
    flag: "FLAG{d0t_d0t_5la5h}",
    hint: "Files live in /var/www/docs/… Try ../../../etc/passwd in the file parameter.",
    learn:
      "Path Traversal: the file parameter is concatenated onto a folder path with no validation, so ../ lets you walk up to any file on the server. Fix: resolve paths and verify they stay inside the allowed directory.",
    render: ({ onReveal }) => <TraversalViewer onReveal={onReveal} />,
  },
  {
    id: "ssrf",
    name: "ProxyFetch · URL Checker",
    category: "Server-Side Request Forgery · OWASP #10",
    filter: "ssrf",
    goal: "SSRF: the server fetches whatever URL you give it. Make it reach its own cloud metadata service.",
    flag: "FLAG{1n73rn4l_f3tch}",
    hint: "It fetches with the server's identity. Try file:///etc/passwd or 169.254.169.254",
    learn:
      "SSRF: the server makes the request, so it carries internal privileges. Pointing it at localhost, file:// or cloud metadata (169.254.169.254) exposes internal systems. Fix: allowlist destinations and block private ranges.",
    render: ({ onReveal }) => <SsrfFetch onReveal={onReveal} />,
  },
  {
    id: "upload",
    name: "PicDrop · Upload",
    category: "Unrestricted Upload · OWASP #8",
    filter: "integrity",
    goal: "File upload: only the front end checks the extension. Upload a script and the server executes it.",
    flag: "FLAG{up10ad_4nd_3x3c}",
    hint: "Pick a file with a .php extension — no server-side checks at all.",
    learn:
      "Unrestricted Upload: files keep their extension and land in a web-served folder, so a .php file becomes a remote code execution backdoor. Fix: validate type + content server-side, rename files, and serve uploads from a non-executable location.",
    render: ({ onReveal }) => <UploadHub onReveal={onReveal} />,
  },
  {
    id: "jwt-forgery",
    name: "CyberBank · Session Token",
    category: "JWT Forgery · OWASP #2",
    filter: "access",
    goal: "The API trusts an unsigned JWT cookie. Decode the payload, flip role to admin, re-encode and verify.",
    flag: "FLAG{jwt_4lg_n0_s3cr3t}",
    hint: "Tokens are just base64 — decode the middle part, change \"role\", re-encode.",
    learn:
      "JWT Forgery: the server base64-decodes the payload and trusts whatever role it says — the signature isn't even verified, so anyone can mint an admin token. Fix: verify signature + alg with a strong secret, use a standard library, and never accept alg:none.",
    render: ({ onReveal }) => <JwtForgery onReveal={onReveal} />,
  },
  {
    id: "nosql-injection",
    name: "MongoShop · Sign In",
    category: "NoSQL Injection · OWASP #3",
    filter: "injection",
    goal: "The login passes your JSON straight into a Mongo query. Use an operator like $ne to bypass the password check.",
    flag: "FLAG{n0sql_$ne_bypass}",
    hint: "Username field accepts JSON — try {\"$ne\":\"\"} in the username.",
    learn:
      "NoSQL Injection: JSON operators ($ne, $gt, $regex) are treated as code, not data, so a crafted username makes the query match the first document regardless of the password. Fix: type-validate inputs, sanitize operators, and never interpolate raw objects into queries.",
    render: ({ onReveal }) => <NosqlLogin onReveal={onReveal} />,
  },
  {
    id: "ssti",
    name: "TemplateCloud · Greeter",
    category: "Server-Side Template Injection · OWASP #3",
    filter: "injection",
    goal: "The greeting renders your name inside a template. Inject {{7*7}} and see it evaluated server-side.",
    flag: "FLAG{sst1_t3mpl4t3}",
    hint: "Type {{7*7}} as the name — if it shows 49, you're in the template engine.",
    learn:
      "SSTI: the app does render(\"Hello \" + name + \"!\") so template expressions are evaluated on the server. Confirming {{7*7}} → 49 proves it, and template engines can escalate to remote code execution. Fix: never concatenate user input into templates; use sandboxed engines and strict validation.",
    render: ({ onReveal }) => <SstiLab onReveal={onReveal} />,
  },
  {
    id: "xxe",
    name: "MegaCorp · XML Import",
    category: "XXE · OWASP #5",
    filter: "injection",
    goal: "The XML parser resolves external entities. Define one that reads a local file and parse it.",
    flag: "FLAG{xxe_f1le_r3ad}",
    hint: "Define a DOCTYPE with an entity pointing at file:///etc/passwd.",
    learn:
      "XXE: an XML parser with external entities enabled lets a crafted DOCTYPE read local files (file://), hit internal URLs, or exfiltrate data. Fix: disable external entities and DTDs entirely — use JSON — or configure the parser to a safe mode.",
    render: ({ onReveal }) => <XxeLab onReveal={onReveal} />,
  },
  {
    id: "cors",
    name: "CyberBank · Balance API",
    category: "CORS Misconfiguration · OWASP #5",
    filter: "access",
    goal: "The API reflects any Origin and allows credentials. Send a request from a malicious origin and read the response.",
    flag: "FLAG{c0rs_r3fl3ct}",
    hint: "The server echoes back the Origin header verbatim — even evil.example.com.",
    learn:
      "CORS Misconfiguration: reflecting every Origin with Access-Control-Allow-Credentials: true hands the browser's authenticated response to any page on the internet — one malicious link reads your balance. Fix: allowlist exact origins, never reflect user-supplied origins, and avoid credentials with wildcards.",
    render: ({ onReveal }) => <CorsLab onReveal={onReveal} />,
  },
  {
    id: "open-redirect",
    name: "login.app · Sign In",
    category: "Open Redirect · OWASP #1",
    filter: "access",
    goal: "After sign-in the app follows the ?next= parameter blindly. Point it at an attacker site.",
    flag: "FLAG{0p3n_r3d1r3ct}",
    hint: "Change ?next= to an external URL like https://evil.example.com",
    learn:
      "Open Redirect: the ?next= parameter is trusted as-is, so the app forwards victims to any site — the perfect phishing scaffold that passes as 'login.app'. Fix: allowlist internal destinations and reject absolute external URLs or scheme-relative tricks.",
    render: ({ onReveal }) => <OpenRedirect onReveal={onReveal} />,
  },
  {
    id: "mass-assignment",
    name: "Springfield · Registration",
    category: "Mass Assignment · OWASP #1",
    filter: "access",
    goal: "The register form binds every submitted field to the account. Add a role field and become admin.",
    flag: "FLAG{m4ss_4ss1gn}",
    hint: "Append {\"role\":\"admin\"} to the form payload.",
    learn:
      "Mass Assignment: the framework binds all request fields straight onto the account object, so a hidden role field silently escalates privileges. Fix: use explicit allowlists of bindable fields (or dedicated DTOs) instead of binding request bodies wholesale.",
    render: ({ onReveal }) => <MassAssign onReveal={onReveal} />,
  },
  {
    id: "dom-xss",
    name: "CareNow · Patient Greeting",
    category: "DOM XSS · OWASP #3",
    filter: "injection",
    goal: "The portal reads the URL hash and writes it into the page with innerHTML. Inject a payload that executes in the browser.",
    flag: "FLAG{d0m_xss_p0rtal}",
    hint: "Trigger a fragment like <img src=x onerror=alert(1)> — the server never even sees it.",
    learn:
      "DOM XSS: the value comes from the URL fragment and is written with innerHTML entirely in the browser — server-side filters never see it. Fix: never write user data with innerHTML; use textContent, encode the context, and set a strict CSP.",
    render: ({ onReveal }) => <DomXss onReveal={onReveal} />,
  },
];
